# Generated by Django 3.2.6 on 2021-08-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210826_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=1, max_length=36),
            preserve_default=False,
        ),
    ]
